import { Header } from "./components";
import "./globals.css";

export const metadata = {
  title: "Alvy Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-4">
        <Header />
        <>{children}</>
      </body>
    </html>
  );
}
